simple_translatable.switcher:
    path: /change-locale/{_locale}
    controller: SimpleTranslatableBundle:LocaleSwitcher:changeLocale
    defaults:
        _locale: "%locale%"
    methods:  [GET]
    options: { i18n: false }
